version: '3.5'
services:
  frontend:
    build:
        context: ./vuejs_frontend
        dockerfile: Dockerfile
    restart: always
    container_name: frontend_app
    ports:
      - "8080:8080"
    volumes:
      - ./vuejs_frontend:/usr/src/app/vuejs_frontend
      - /usr/src/app/vuejs_frontend/node_modules
    networks:
      - app-network

  backend:
    build:
        context: ./DjangoBackend
        dockerfile: Dockerfile
    restart: always
    container_name: django_server
    volumes:
      - ./DjangoBackend:/pfe/backend
      - avito-logs-volume:/pfe/backend/logs
    ports:
      - "8000:8000"
    links:
      - mongodb
    depends_on:
      - "mongodb"
    networks:
      - app-network
  
  scrapy-service:
    build:
        context: ./avito
        dockerfile: Dockerfile
    restart: always
    container_name: scrapy_server
    volumes:
      - ./avito:/pfe/avito-scrapy-server
      - avito-logs-volume:/pfe/avito-scrapy-server/logs
    ports:
      - "6800:6800"
    networks:
      - app-network
  
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    volumes: 
        - ./data/elasticsearch:/usr/share/elasticsearch/data
    env_file: 
        - elasticsearch.env
    ports: 
        - "9200:9200"
    healthcheck:
      test: "wget -q -O - http://localhost:9200/_cat/health"
      interval: 1s
      timeout: 30s
      retries: 300
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-network

  kibana:
    image: kibana:7.7.0
    container_name: kibana
    env_file: 
      - kibana.env
    ports: 
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - app-network
  
  monstache:
    build:
        context: ./monstache
        dockerfile: Dockerfile
    container_name: monstache
    # expose:
    #   - "8080"
    # ports:
    #   - "8080:8080"
    depends_on:
      - elasticsearch
      - mongodb
      - mongodb1
      - mongodb2
    links:
      - elasticsearch
    networks:
      - app-network
      

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb_server
    volumes:
      - mongodata:/data/db
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
    networks:
      - app-network

  mongodb1:
    image: mongo:latest
    restart: always
    container_name: mongodb1_server
    volumes:
      - mongodata1:/data/db
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
    networks:
      - app-network

  mongodb2:
    image: mongo:latest
    restart: always
    container_name: mongodb2_server
    volumes:
      - mongodata2:/data/db
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]    
    networks:
      - app-network

  mongosetup:
    build:
      context: ./mongo-setup
      dockerfile: Dockerfile
    container_name: "mongosetup"
    depends_on:
      - mongodb
    volumes:
      - mongostatus:/data/
    networks:
      - app-network
  


volumes:
  avito-logs-volume:
  mongodata:
  mongodata1:
  mongodata2:
  mongostatus:

networks:
  app-network:
    driver: bridge