mongo-url = "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/avito?replicaSet=replication"
elasticsearch-urls = ["http://elasticsearch:9200"]
elasticsearch-max-conns = 4
elasticsearch-max-seconds = 5
elasticsearch-max-bytes = 8000000
dropped-collections = true
dropped-databases = true

direct-read-namespaces = ["avito.products"]
change-stream-namespaces = ["avito.products"]
stats = false
resume = true

[[mapping]]
namespace = "avito.products"
index = "products_index"