mongo-url = "mongodb://mongodb:27017,mongodb1:27017,mongodb2:27017/avito?replicaSet=rsmongo"
elasticsearch-urls=['http://elasticsearch:9200/']
elasticsearch-max-conns = 4
elasticsearch-max-seconds = 5
elasticsearch-max-bytes = 8000000
dropped-collections = true
dropped-databases = true

namespace-regex = "^avito"
direct-read-namespaces = ["product"]

gzip = true
stats = true
replay = false
resume = true
resume-write-unsafe = false
resume-name = "default"
verbose = true
exit-after-direct-reads = false
